let token='',store={bookings:[],closedDates:[],slotTimes:[],dateSchedules:{}},selectedDate='';
const $=s=>document.querySelector(s),api=(url,opts={})=>fetch(url,{...opts,headers:{'content-type':'application/json',authorization:'Bearer '+token,...opts.headers}}).then(async r=>({ok:r.ok,data:await r.json()}));
const pad=n=>String(n).padStart(2,'0'),isoDate=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,fromISO=s=>{const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d,12)},prettyDate=s=>fromISO(s).toLocaleDateString('ru-RU',{weekday:'long',day:'numeric',month:'long'}),shortDate=s=>fromISO(s).toLocaleDateString('ru-RU',{weekday:'short',day:'numeric',month:'short'}),holiday=s=>{const d=fromISO(s);return [[1,1],[1,2],[1,3],[1,4],[1,5],[1,6],[1,7],[1,8],[2,23],[3,8],[5,1],[5,9],[6,12],[11,4]].some(([m,day])=>d.getMonth()+1===m&&d.getDate()===day)};
function setNotice(message){$('#admin-notice').textContent=message}
$('#toggle-password').onclick=()=>{const field=$('#login-form').elements.password,visible=field.type==='password';field.type=visible?'text':'password';$('#toggle-password').textContent=visible?'Скрыть':'Показать';$('#toggle-password').setAttribute('aria-label',visible?'Скрыть пароль':'Показать пароль')};
$('#login-form').onsubmit=async e=>{e.preventDefault();const r=await api('/api/admin/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});if(!r.ok){$('#login-message').textContent=r.data.error;return}token=r.data.token;$('#login').hidden=true;$('#dashboard').hidden=false;await load(true)};
async function load(initial=false){const r=await api('/api/admin/bookings');if(!r.ok){setNotice(r.data.error||'Не удалось загрузить расписание');return}store=r.data;if(initial||!selectedDate)selectedDate=isoDate(new Date());renderDates();await loadDay(selectedDate)}
function renderDates(){const holder=$('#date-list');holder.replaceChildren();const start=fromISO(isoDate(new Date()));for(let i=0;i<31;i++){const date=new Date(start);date.setDate(start.getDate()+i);const value=isoDate(date),closed=holiday(value)||store.closedDates.includes(value),b=document.createElement('button');b.type='button';b.className='date-button'+(value===selectedDate?' selected':'')+(closed?' closed-date':'');const title=document.createElement('b');title.textContent=shortDate(value);const status=document.createElement('span');status.textContent=closed?'Выходной':'Открыто';b.append(title,status);b.onclick=()=>selectDate(value);holder.append(b)}}
async function selectDate(value){selectedDate=value;renderDates();await loadDay(value);if(!$('#manual-booking').hidden){$('#manual-date').value=value;await populateManualTimes()}}
function currentTimes(){return Object.hasOwn(store.dateSchedules||{},selectedDate)?store.dateSchedules[selectedDate]:(store.slotTimes||[])}
async function loadDay(date){const response=await api('/api/slots?date='+encodeURIComponent(date));if(!response.ok){setNotice(response.data.error||'Не удалось загрузить день');return}const holidayClosed=response.data.holiday;$('#selected-date').textContent=prettyDate(date);$('#editor-date-label').textContent=prettyDate(date);$('#day-status').textContent=holidayClosed?'Выходной':`${response.data.slots.length} окошек`;$('#day-status').classList.toggle('closed',holidayClosed);setNotice('');const holder=$('#admin-times');holder.replaceChildren();const dayBookings=store.bookings.filter(b=>b.date===date&&b.status==='confirmed');if(holidayClosed&&!dayBookings.length){const p=document.createElement('p');p.className='empty-day';p.textContent='В этот день примерки не проводятся.';holder.append(p);return}if(holidayClosed)setNotice('День отмечен как выходной, но существующие записи оставлены в расписании.');const slots=holidayClosed?response.data.slots.filter(slot=>dayBookings.some(b=>b.time===slot.time)):response.data.slots;if(!slots.length){const p=document.createElement('p');p.className='empty-day';p.textContent='На этот день нет доступных окошек. Добавьте их в редакторе расписания.';holder.append(p);return}for(const slot of slots){const row=document.createElement('div');row.className='schedule-row';const time=document.createElement('div');time.className='schedule-time';time.textContent=slot.time;const info=document.createElement('div');info.className='appointment-info';const booking=dayBookings.find(b=>b.time===slot.time);if(booking){const name=document.createElement('b');name.textContent=booking.name;const contact=document.createElement('span');contact.textContent=booking.phone;info.append(name,contact);if(booking.note){const note=document.createElement('small');note.textContent=' · '+booking.note;info.append(note)}if(booking.dresses?.length){const details=document.createElement('details'),summary=document.createElement('summary'),dresses=document.createElement('small');summary.textContent='Платья клиентки';dresses.textContent=booking.dresses.join(', ');details.append(summary,dresses);info.append(details)}const cancel=document.createElement('button');cancel.type='button';cancel.className='cancel-booking';cancel.textContent='Отменить';cancel.onclick=()=>cancelBooking(booking);row.append(time,info,cancel)}else{const free=document.createElement('span');free.className='free-label';free.textContent='Свободно';info.append(free);row.append(time,info)}holder.append(row)}}
async function cancelBooking(booking){if(!window.confirm(`Отменить запись ${booking.name} на ${prettyDate(booking.date)} в ${booking.time}?`))return;const r=await api('/api/admin/bookings/'+encodeURIComponent(booking.id),{method:'DELETE'});if(!r.ok){setNotice(r.data.error||'Не удалось отменить запись');return}await load();setNotice('Запись отменена.')}
$('#open-manual').onclick=()=>{const panel=$('#manual-booking');panel.hidden=!panel.hidden;if(!panel.hidden){$('#manual-date').value=selectedDate;$('#manual-message').textContent='';populateManualTimes();panel.scrollIntoView({behavior:'smooth',block:'center'})}};
$('#close-manual').onclick=()=>{$('#manual-booking').hidden=true};$('#manual-date').onchange=async()=>{selectedDate=$('#manual-date').value;renderDates();await loadDay(selectedDate);await populateManualTimes()};
async function populateManualTimes(){const select=$('#manual-time');select.replaceChildren();const empty=document.createElement('option');empty.value='';empty.textContent='Выберите время';select.append(empty);if(!$('#manual-date').value)return;const r=await api('/api/slots?date='+encodeURIComponent($('#manual-date').value));if(!r.ok||r.data.holiday)return;for(const slot of r.data.slots.filter(x=>!x.taken)){const option=document.createElement('option');option.value=slot.time;option.textContent=slot.time;select.append(option)}}
$('#admin-booking-form').onsubmit=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target)),r=await api('/api/admin/book',{method:'POST',body:JSON.stringify(body)});if(!r.ok){$('#manual-message').textContent=r.data.error||'Не удалось сохранить запись.';await populateManualTimes();return}e.target.reset();$('#manual-booking').hidden=true;await load();setNotice(`Клиентка записана на ${body.time}.`)};
$('#edit-schedule').onclick=()=>{const editor=$('#schedule-editor');editor.hidden=!editor.hidden;if(!editor.hidden)beginEdit()};$('#cancel-edit').onclick=()=>{$('#schedule-editor').hidden=true};
function beginEdit(){const booked=new Set(store.bookings.filter(b=>b.date===selectedDate&&b.status==='confirmed').map(b=>b.time)),times=currentTimes(),holder=$('#editor-times');holder.replaceChildren();$('#closed-day').checked=store.closedDates.includes(selectedDate);for(const value of times)addEditorTime(value,booked.has(value));$('#new-time').value='10:00'}
function addEditorTime(value,locked=false){const row=document.createElement('div');row.className='editor-time';const input=document.createElement('input');input.type='time';input.value=value;input.required=true;input.disabled=locked;input.dataset.locked=String(locked);const remove=document.createElement('button');remove.type='button';remove.className='remove-time';remove.textContent=locked?'Время занято записью':'Убрать';remove.disabled=locked;remove.onclick=()=>row.remove();row.append(input,remove);$('#editor-times').append(row)}
$('#add-time').onclick=()=>{const value=$('#new-time').value;if(!value){setNotice('Выберите время для нового окошка.');return}if([...$('#editor-times').querySelectorAll('input')].some(input=>input.value===value)){setNotice('Такое время уже есть в расписании.');return}addEditorTime(value);setNotice('')};
$('#save-schedule').onclick=async()=>{const slotTimes=[...$('#editor-times').querySelectorAll('input')].map(input=>input.value).filter(Boolean);if(new Set(slotTimes).size!==slotTimes.length){setNotice('В расписании не должно быть одинаковых окошек.');return}slotTimes.sort();const closed=$('#closed-day').checked,r=await api('/api/admin/schedule',{method:'PUT',body:JSON.stringify({date:selectedDate,slotTimes,closed})});if(!r.ok){setNotice(r.data.error||'Не удалось сохранить расписание.');return}$('#schedule-editor').hidden=true;await load();setNotice('Расписание сохранено.')};
