const q=new URLSearchParams(location.search),dresses=q.get('d')?.split(',').filter(Boolean).map(item=>{const [id,size]=item.split(':');return{id,size,names:{1:'Amaris',2:'Elodie',3:'Aurelia',4:'Celeste',5:'Genevieve',6:'Seraphine'}}})||[];let choice={date:'',time:''};const $=s=>document.querySelector(s),dateName=d=>new Intl.DateTimeFormat('ru-RU',{weekday:'short',day:'numeric',month:'long'}).format(new Date(d+'T12:00:00'));
$('#dresses').textContent=dresses.length?'Вы выбрали: '+dresses.map(x=>x.names[x.id]+' — '+x.size+' размер').join(', '):'Платья из корзины не выбраны — но мы всё равно будем рады вам.';
const holiday=iso=>{const [,m,d]=iso.split('-').map(Number);return [[1,1],[1,2],[1,3],[1,4],[1,5],[1,6],[1,7],[1,8],[2,23],[3,8],[5,1],[5,9],[6,12],[11,4]].some(([mm,dd])=>m===mm&&d===dd)};
const localISO=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
async function api(url,options){const response=await fetch(url,options);if(!response.headers.get('content-type')?.includes('application/json'))throw new Error('API unavailable');const data=await response.json();return{ok:response.ok,data}}
for(let i=0;i<30;i++){const date=new Date();date.setDate(date.getDate()+i);const iso=localISO(date),b=document.createElement('button');b.className='day';b.type='button';b.dataset.date=iso;b.innerHTML=`<b>${date.toLocaleDateString('ru-RU',{day:'numeric',month:'short'})}</b><span>${date.toLocaleDateString('ru-RU',{weekday:'short'})}</span>`;if(holiday(iso)){b.classList.add('closed');b.disabled=true}else b.onclick=()=>loadSlots(iso,b);$('#days').append(b)}
let slotRequest=0;
async function loadSlots(date,button){const request=++slotRequest;choice={date,time:''};document.querySelectorAll('.day').forEach(x=>x.classList.toggle('active',x===button));$('#selected-date').textContent=dateName(date);$('#slots').textContent='Загружаем время…';$('#message').textContent='';try{const result=await api('/api/slots?date='+encodeURIComponent(date));if(request!==slotRequest)return;if(!result.ok)throw new Error(result.data.error||'Сервер записи недоступен. Попробуйте позже.');const data=result.data;if(data.holiday){button.classList.add('closed');button.disabled=true;$('#slots').textContent='В этот день примерки не проводятся.';return}$('#slots').replaceChildren();if(!data.slots.length){$('#slots').textContent='На этот день нет свободных окошек.';return}data.slots.forEach(s=>{const b=document.createElement('button');b.className='slot'+(s.taken?' taken':'');b.textContent=s.time;b.disabled=s.taken;b.onclick=()=>{choice.time=s.time;document.querySelectorAll('.slot').forEach(x=>x.classList.remove('active'));b.classList.add('active')};$('#slots').append(b)})}catch(error){if(request!==slotRequest)return;$('#slots').textContent=error.message==='API unavailable'?'Сервер записи не подключён. Попробуйте позже.':error.message||'Не удалось загрузить время. Попробуйте позже.'}}
const bookingForm=$('#booking-form'),bookingButton=bookingForm.querySelector('button[type="submit"]'),nameInput=bookingForm.elements.name,phoneInput=bookingForm.elements.phone;
function updateBookingButton(){const ready=nameInput.value.trim().length>=2&&phoneInput.value.trim().length>=7;bookingButton.disabled=!ready;bookingButton.style.backgroundColor=ready?'':'#b9b1aa';bookingButton.style.cursor=ready?'pointer':'not-allowed'}
nameInput.addEventListener('input',updateBookingButton);phoneInput.addEventListener('input',updateBookingButton);bookingForm.addEventListener('reset',()=>setTimeout(updateBookingButton,0));updateBookingButton();
bookingForm.onsubmit=async e=>{e.preventDefault();if(!choice.date||!choice.time){$('#message').textContent='Сначала выберите дату и время.';return}const form=new FormData(e.target),body={...Object.fromEntries(form),...choice,dresses:dresses.map(x=>x.names[x.id]+' · размер '+x.size)};bookingButton.disabled=true;try{const result=await api('/api/book',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(result.ok){const when=dateName(choice.date)+' в '+choice.time;location.href='index.html?booking=success&when='+encodeURIComponent(when)}else $('#message').textContent=result.data.error||'Не удалось записаться. Попробуйте ещё раз.'}catch{$('#message').textContent='Сервер записи недоступен. Попробуйте позже.'}finally{updateBookingButton()}};
